# Generated by Django 5.2.8 on 2025-11-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteEvent',
            fields=[
                ('event_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('event_image', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_hour', models.CharField(max_length=100)),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_city', models.CharField(max_length=100)),
                ('venue_state', models.CharField(max_length=100)),
                ('venue_address', models.CharField(max_length=100)),
                ('event_url', models.CharField(max_length=100)),
            ],
        ),
    ]
