# Generated by Django 5.2.8 on 2025-11-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteevent',
            name='event_date',
            field=models.CharField(max_length=100),
        ),
    ]
