# Generated by Django 5.2.8 on 2025-11-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_favoriteevent_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_hour',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_image',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='event_url',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='venue_city',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='venue_name',
        ),
        migrations.RemoveField(
            model_name='favoriteevent',
            name='venue_state',
        ),
    ]
