# Generated by Django 5.2.8 on 2025-11-28 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_remove_favoriteevent_event_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevent',
            name='displayOnProfile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='displayPriority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='favoriteevent',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
