# Generated by Django 5.2.8 on 2025-11-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_favoriteevent_displayonprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='favoriteevent',
            name='event_id',
            field=models.CharField(max_length=100),
        ),
    ]
